apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  repositories: |
    - name: ecr
      type: ecr
      registry_url: 590184029746.dkr.ecr.us-east-1.amazonaws.com/test1 # e.g., xxxxxxx.dkr.ecr.region.amazonaws.com
      aws_region: us-east-1 # e.g., us-east-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-image-updater
  template:
    metadata:
      labels:
        app: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      containers:
        - name: argocd-image-updater
          image: argoprojlabs/argocd-image-updater:latest
          env:
            - name: ARGOCD_SERVER
              value: argocd-server.argocd.svc.cluster.local:443
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: T7mp7BcCVtVxabog
