apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-container
      image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-app:v1.0  # Invalid image tag or ECR access issues or invalid image name
