apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-mismatch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-mismatch
  template:
    metadata:
      labels:
        app: label-mismatch
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
